using UnityEngine;

public class MovimientoArribaAbajo : MonoBehaviour
{
    public float velocidad = 1.0f; // Velocidad del movimiento
    public float rango = 1.0f; // Rango de movimiento

    private Vector3 posicionInicial;

    void Start()
    {
        // Guarda la posici贸n inicial del objeto
        posicionInicial = transform.position;
    }

    void Update()
    {
        // Calcula la posici贸n objetivo basada en la posici贸n inicial y el rango
        Vector3 posicionObjetivo = posicionInicial + Vector3.up * Mathf.Sin(Time.time * velocidad) * rango;

        // Mueve el objeto hacia la posici贸n objetivo
        transform.position = posicionObjetivo;
    }
}

